name: Test Workflow

on:
  workflow_dispatch:  # This will allow the workflow to be triggered manually

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print a message
      run: echo "The workflow has been triggered!"
